[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


